SongCMS/urls.py
#coding:utf-8
"""SongCMS URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url,include
from django.contrib import admin
from blog.feed import AllAriclesRssFeed
import xadmin

'''Django匹配URL是在该项目目录下的urls.py中完成，因此，要把blog应用下的urls.py包含到该文件中，
'''
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^blog/',include('blog.urls')), #Django将r后面的字符串和后面的include的urls.py文件进行拼接
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllAriclesRssFeed(),name='rss'), #设置首页面RSS的URL为/all/rss
    url(r'^search/',include('haystack.urls')), #这里的urls.py Django已经帮我们写好了,只要有在settings.py中配置
]

blog/urls.py
#coding=utf-8
__author__ = 'CoderSong'
__date__ = '2019/4/15 20:32'

from django.conf.urls import url
from . import views

'''这里将url与视图函数绑定:
    这里的(?P<pk>[0-9]+)是由python定义匹配规则，
    作用是从用户访问的URL里把括号内匹配的字符串捕获出来，并传递对应的视图函数detail。
    实际上视图函数调用方式如detail(request,pk=255)
'''

'''app_name='blog' 告诉 Django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间 
'''
app_name = 'blog'


#URL与视图函数的绑定,url()中的第二个参数必须是函数，
# 而IndexView是一个类，因此使用类视图的as_view()方法将其转换为视图函数
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^arcticle/(?P<pk>[0-9]+)/$',views.ArticleDetailView.as_view(),name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
]

comments/urls.py
#coding=utf-8
__author__ = 'CoderSong'
__date__ = '2019/4/16 22:08'

from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/artcile/(?P<article_pk>[0-9]+)/$',views.article_commnet,name='article_comment'),
]

blog/models.py
#coding=utf-8

from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import  AbstractUser,User
import datetime
from django.utils import timezone
from django.core.urlresolvers import reverse
import markdown
from django.utils.html import strip_tags
# Create your models here.

class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=50, verbose_name=u'昵称', default='')  # 昵称
    birday = models.DateField(verbose_name=u'生日', null=True, blank=True)
    gender = models.CharField(max_length=20, choices=(('male', u'男'), ('female', '女')), default='female')
    address = models.CharField(max_length=100, verbose_name=u'地址', default=u'')
    phonenumber = models.CharField(max_length=11, null=True, blank=True)

    class Meta:
        '''定义表的Meta信息
        '''
        #定义在管理后台显示的名称
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.username  # 因为我们已经继承了AbstractUser,而这里的username在AbstractUser这个类中


class Category(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=20,unique=True,verbose_name=u'类别')
    desc = models.TextField(verbose_name=u'详情')

    class Meta:
        verbose_name_plural = verbose_name = u'类别'

    def __unicode__(self):
            return self.name

class Tag(models.Model):
    name = models.CharField(max_length=20,verbose_name=u'标签')

    class Meta:
        verbose_name_plural = verbose_name = u'标签'

    def __unicode__(self):
        return self.name

# class Comment(models.Model):
#     id = models.AutoField(primary_key=True)
#     name = models.CharField('评论用户', max_length=20)
#     email = models.EmailField('邮箱')
#     content = models.TextField('内容')
#     publish = models.DateField('时间', auto_now=True)
#     article = models.ForeignKey('Article', on_delete=models.CASCADE, verbose_name='文章')
#     reply = models.ForeignKey('self', on_delete=models.DO_NOTHING, null=True, blank=True, verbose_name='回复')
#
#     class Meta:
#         verbose_name_plural = verbose_name = '评论'
#
#     def __str__(self):
#         return self.content


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(UserProfile,on_delete=models.DO_NOTHING,verbose_name=u'作者')
    title =  models.CharField(max_length=50,verbose_name=u'标题')
    abstract = models.CharField(max_length=300,blank=True,verbose_name=u'摘要')
    content = models.TextField(verbose_name=u'内容',default='')
    category = models.ForeignKey(Category,on_delete=models.SET_DEFAULT,default=1,verbose_name=u'类别')
    pub_date = models.DateField(auto_now_add=True,editable=True)
    tag = models.ManyToManyField(Tag,verbose_name=u'标签')
    picture = models.CharField(max_length=200,blank=True)   #标题图片地址
    views_num = models.PositiveIntegerField(default=0)  # PositiveIntegerField 类型只允许值为非负整数

    class Meta:
        verbose_name_plural = verbose_name = u'文章'
        ordering = ['-pub_date'] #Django允许我们直接在model.Model的子类中定义一个Meta类，在这个类中指定一些属性来规定子类属性

    def __unicode__(self):
        return self.title


    ''' 01增加Article模型方法 
        在article类中定义一个get_absolute_url方法，生成自己的url
        这里的reverse函数第一个参数值是'blog:detail'，意思是blog应用下的name=detail函数（blog/urls.py中定义）
        第二个参数是将detail的正则表达式参数被后面的参数pk换掉，最终生成一个article/24这样的URL
    '''
    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})


    '''02增加Aticle模型方法
        一旦用户访问了某篇文章，这时将views_num值 +1， 由于这个过程较为单一，因此最好在模型子类中自定义。
    '''
    def increase_views_num(self):
        self.views_num += 1    #将自身值+1
        self.save(update_fields=['views_num'])#然后将调用save方法将其保存在数据库中，Django 中使用update_field字段来更新数据库中的views_num字段


    '''03 复写save方法从文章内容中提取前N个字符作为文章的摘要
        但前提是在admin后台并未为文章添加摘要
    '''
    def save(self,*args,**kwargs):
        if not self.abstract:
            '''这里要用markdown的目的是可能我们在后台添加的文章有一定的格式如富文本形式，
                我们需要先转为HTML文本形式，然后再去掉HTML标签
            '''
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra', # 先转为HTML文本，
                'markdown.extensions.codehilite',  # 然后去掉HTML文本中的标签
            ])

            self.abstract = strip_tags(md.convert(self.content))[:54]

        #调用父类的save方法，将数据保存在数据库中
        super(Article,self).save(*args,**kwargs)

comments/models.py
#coding=utf-8
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    comment_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey('blog.Article')

    class Meta:
        verbose_name_plural = verbose_name = u'评论'

    def __unicode__(self):
        return self.text[:20]

blog/views.py
#coding=utf-8
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView,DetailView
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from models import Article,Tag,Category
from django.http import JsonResponse,HttpResponse
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
import markdown
from comments.forms import CommentForm
from django.db.models import Q


# Create your views here.
def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = "请输入关键词"
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    article_list = Article.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'article_list': article_list})


'''Web服务器的作用是接受来自用户的http请求，根据请求内容，将处理结果包装成HTTP响应返回给用户
    视图函数首先接受一个名为request的参数，这个参数就是Djang为我们封装好的HTTP请求，
    然后返回响应，这个响应由HttpResponse封装，我们给它传递了一个自定义的字符串
'''

'''01 
   这里的render函数根据我们传入的参数来构成一个HttpResponse。
   其中，第一个参数表示Http请求，第二个参数表示找到blog/index.html这个模板并读取其中的内容，
   第三个参数表示将模板中的变量替换为我们要传递的变量值。即{{title}}替换为‘我的博客首页’，
   {{welcome}}替换为‘欢迎访问我的博客首页’；
   整个的内容被传递给HttpResponse对象，并返回给浏览器，这一过程由render隐式地完成。
'''
# def index(request):
#     latest_article_list = Article.objects.all()  #这是定义的获取文章列表操作是通过视图函数从数据库中获取文章列表
#     # context = {'latest_article_list':latest_article_list}
#     return  render(request,'blog/index.html',context={'title':'我的博客首页',
#                                                       'welcome':'欢迎访问我的博客首页',
#                                                       'latest_article_list':latest_article_list})
#
#     # return HttpResponse('欢迎访问我的博客首页！')


''' 02
    书写获取文章内容函数
    这里的detail()视图函数用到了Python的markdown模块，同时需要在虚拟环境下安装Pygment，
    用于高亮显示，如CSDN中的博客代码显示
'''

# def detail(request,pk):
#     article = get_object_or_404(Article,pk=pk) #从数据库中获取文章
#     '''定义阅读量自增
#         一旦用户点击了文章详细，即detail()视图函数一旦被调用，说明该文章被访问一次
#         调用Article数据模型中increase_views_num方法，实现views_num自增
#     '''
    # article.increase_views_num()
    #
    # article.content = markdown.markdown(article.content,
    #                                     extensions=[
    #                                         'markdown.extensions.extra',
    #                                         'markdown.extensions.codehilite',
    #                                         'markdown.extensions.toc',
    #                                     ])
    #
    # form = CommentForm()
    # comment_list = article.comment_set.all()
    # context = {'article': article,
    #            'form': form,
    #            'comment_list': comment_list
    #            }
    # return render(request, 'blog/detail.html', context=context)



'''03
    显示某个归档日期下的文章列表
'''
# def archives(request,year,month):
#     article_list = Article.objects.filter(pub_date__year = year,
#                                           pub_date__month = month)
#     return render(request,'blog/index.html',context={'article_list':article_list})


'''04
    书写分类页面d的视图函数
'''
# def category(request,pk):
#     cate = get_object_or_404(Category,pk=pk)
#     article_list = Article.objects.filter(category=cate) #这里传递的pk在base.html模板中定义的是categort.pk，即过滤出该类别下的文章列表
#     return render(request,'blog/index.html',context={'article_list':article_list})

'''05书写指定标签下文章列表视图函数
'''

'''从上面的视图函数可以看出，它们在处理数据对象时的方法非常类似，先从数据库中抽取数据，然后交给渲染模板。
    Django用基于类的通用视图函数来定义取代这些重复的部分
'''


class IndexView(ListView):
    model = Article  #指定要获取数据列表的数据模型
    template_name = 'blog/index.html'     #指定视图函数所渲染的模板
    context_object_name = 'latest_article_list'
    paginate_by = 3 #在类视图ListView中已经帮我们写好了分页逻辑，只需要在类视图中指定属性值就好

    def get_context_data(self, **kwargs):
        context = super(IndexView,self).get_context_data(**kwargs) #获得父类生成的并传递给模板的字典
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')#如果总的文章数量小于每页要展示的文章数量，那么不需要分页，该布尔值为False

        pagination_data = self.pagination_data(paginator,page,is_paginated)
        context.update(pagination_data)
        return context

    #定义如何显示分页
    def pagination_data(self,paginator,page,is_paginated):
        if not is_paginated:  #如果没有分页，则不显示分页导航信息
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = list(paginator.page_range)

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data





class ArchivesView(IndexView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'



class ArticleDetailView(DetailView):
    #这里的属性与ListView属性相同
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get(self,request,*args,**kwargs):
        # 这里只有重写get方法才能调用increase_views_num()方法
        response = super(ArticleDetailView,self).get(request,*args,**kwargs)
        self.object.increase_views_num()
        #视图函数必须有返回值
        return response


    #编写get_object()方法的目的是需要对article的content值进行渲染
    def get_object(self, queryset=None):
        article = super(ArticleDetailView,self).get_object(queryset=None)

        #实例化一个markdown.markdown类，并传入参数
        md = markdown.Markdown(extensions=[
                                'markdown.extensions.extra',      # 转换html结构文本
                                'markdown.extensions.codehilite', #高亮标记代码
                                TocExtension(slugify=slugify),        #自动生成文章目录
                               ])
        article.content = md.convert(article.content)    #利用实例方法convert()将文章内容渲染成HTML文本
        article.toc = md.toc                             #给文章添加目录
        return article


    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView,self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list
        })
        return context



class CategoryView(IndexView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name =  'article_list'

    '''由于上面的CategoryView类视图获取的是该数据模型下所有的列表，
        但是为了获取指定分类下的文章列表，我们需要重写父类的get_queryset()方法
    '''
    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk')) #得到指定分类
        return super(CategoryView,self).get_queryset().filter(category=cate)


class TagView(IndexView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tag=tag)

templates/blog/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <style>
        span.highlighted{
            color: red;
        }
    </style>


    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <!--用来提供代码高亮样式的,选择一个你喜欢的样式文件-->
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

</head>
<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search"  name='q' placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>

                </div><!-- col-md-8 -->
        </div>
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>

            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class='widget-title'>最新文章</h3>
                    {% get_recent_artciles as recent_article_list %}
                    <ul>
                        {% for article in recent_article_list %}
                        <li>
                            <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章!
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a>
                            </li>
                        {% empty %}
                            暂无归档
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-category">
                    <h3 class="widget-list">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk%}">{{ category.name }}<span class="article-count">({{ category.num_articles }})</span></a>
                        </li>
                        {% empty %}
                            暂无分类
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                        暂无标签
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% block bottom %}
                {% endblock bottom %}
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="#">博客</a></li>
            <li><a href="#">关于</a></li>
            <li><a href="#">联系</a></li>
        </ul>
    </nav>
</div>
<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

templates/blog/detail.html
{% extends 'blog/base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>
</head>
<body id="single">
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                <article class="article artcile-1">
                    <header class="entry-header">
                        <h1 class="article-title">{{ article.title }}</h1>
                        <div class="article-meta">
                            <span class="artcile-category"><a href="{% url 'blog:category' article.category.pk%}">{{ article.category }}</a></span>
                            <span class="article-date"><a href="#"><time class="article-date"
                                                                      datetime="article.pub_date">{{ article.pub_date }}</time></a></span>
                            <span class="article-author"><a href="#">{{ article.author }}</a></span>
                            <span class="comments-link">
                                <a href="{% url 'blog:detail' article.pk %}#comment-area">评论{{ article.comment_set.count }}</a></span>
                            <span class="views-count"><a href="{% url 'blog:detail' article.pk %}">阅读{{ article.views_num }}</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                     {{ article.content|safe}}
                        <div class="widget-tag-cloud">
                            <ul>
                                标签：
                                {% for tag in article.tag.all %}
                                    <li><a href="{% url 'blog:tag' tag.pk %}">#{{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:article_comment' article.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">URL：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-8">
                                <label for="{{ form.text.id_for_label }}">内容：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div><!-- row -->
                    </form>
                    <div >
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ article.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{comment.name}}</span>
                                <time class="submit-date">{{ comment.comment_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                    </div>
                </section>
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                    <div class="widget widget-content">
                        <h3 class="widget-title">文章目录</h3>
                        {{ article.toc|safe }}
                    </div>
                {% endblock toc %}
            </aside>
        </div>
    </div>
</div>
</body>
</html>